# Generated by Django 4.2.1 on 2023-05-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='User')),
                ('advert_name', models.CharField(default='Advert')),
                ('link', models.CharField()),
                ('id_avito', models.CharField(max_length=20)),
                ('post_time', models.DateTimeField()),
                ('address', models.CharField(default='Adress')),
                ('detailing', models.TextField(default='Detailing')),
                ('tel', models.CharField(max_length=20)),
                ('source', models.CharField(default='Rest')),
            ],
        ),
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(blank=True, null=True)),
                ('number', models.CharField(blank=True, null=True)),
                ('taken_from_call_id', models.CharField(blank=True, null=True)),
                ('line_number', models.CharField(blank=True, null=True)),
                ('acd_group', models.CharField(blank=True, null=True)),
                ('was_transferred', models.BooleanField(default=False)),
                ('hold_initiator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField()),
                ('call_id', models.CharField()),
                ('timestamp', models.IntegerField()),
                ('seq', models.IntegerField()),
                ('call_state', models.CharField()),
                ('location', models.CharField()),
                ('disconnect_reason', models.IntegerField(blank=True, null=True)),
                ('transfer', models.CharField(blank=True, null=True)),
                ('sip_call_id', models.CharField(blank=True, null=True)),
                ('command_id', models.CharField(blank=True, null=True)),
                ('task_id', models.CharField(blank=True, null=True)),
                ('callback_initiator', models.CharField(blank=True, null=True)),
                ('send_flag', models.BooleanField(blank=True, default=False)),
                ('from', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', related_query_name='from', to='mangoapi.caller', verbose_name='from')),
                ('to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', related_query_name='to', to='mangoapi.caller', verbose_name='to')),
            ],
        ),
    ]
