# Generated by Django 4.2.1 on 2023-05-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='from',
        ),
        migrations.RemoveField(
            model_name='call',
            name='to',
        ),
        migrations.AddField(
            model_name='call',
            name='from_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='mangoapi.caller', verbose_name='from_user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='call',
            name='to_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='mangoapi.caller', verbose_name='to_user'),
            preserve_default=False,
        ),
    ]
