# Generated by Django 4.2.1 on 2023-05-24 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangoapi', '0003_alter_call_send_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='from_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_user', to='mangoapi.caller', verbose_name='from_user'),
        ),
        migrations.AlterField(
            model_name='call',
            name='to_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_user', to='mangoapi.caller', verbose_name='to_user'),
        ),
    ]
