# Generated by Django 4.2.1 on 2023-05-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangoapi', '0004_alter_call_from_user_alter_call_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='from_user',
            field=models.OneToOneField(on_delete=models.SET(0), related_name='from_user', to='mangoapi.caller', verbose_name='from_user'),
        ),
        migrations.AlterField(
            model_name='call',
            name='to_user',
            field=models.OneToOneField(on_delete=models.SET(0), related_name='to_user', to='mangoapi.caller', verbose_name='to_user'),
        ),
    ]
