# Generated by Django 4.2.1 on 2023-05-24 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangoapi', '0005_alter_call_from_user_alter_call_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='from_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='from_user', to='mangoapi.caller', verbose_name='from_user'),
        ),
        migrations.AlterField(
            model_name='call',
            name='to_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='to_user', to='mangoapi.caller', verbose_name='to_user'),
        ),
    ]
