# Generated by Django 4.2.1 on 2023-05-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangoapi', '0006_alter_call_from_user_alter_call_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgNotifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField()),
                ('massage', models.TextField()),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('send_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
